# Generated by Django 3.0.6 on 2020-06-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='comments',
        ),
    ]
