# Generated by Django 3.0.6 on 2020-06-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_todolist_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
