# Generated by Django 3.0.6 on 2020-06-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todolist_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='title',
            new_name='item',
        ),
    ]
