# Generated by Django 3.0.6 on 2020-06-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_todolist_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.CharField(max_length=20),
        ),
    ]
